### ISSUE TITLE
Equipped slot indicator obscures offset window indicator

### ISSUE THREAD

**Issue by jordanbtucker** [iTNTPiston/botw-hundo-dupl#12]
When an item is equipped, its slot is displayed with a blue background, similar to how it looks in game. However, this obscures the red background used to indicate that a slot is included in the offset window.

In this example, the inventory has four slots, two of which are in the offset window, but since the third slot contains an equipped shield, there is no visual indication that the slot is also included in the offset window. One must count the slots to determine whether a slot with an equipped item is within the offset window, which can be tedious and error prone for large inventories.

![image](https://user-images.githubusercontent.com/468153/182983646-9b75ea91-020d-45b2-9b0c-d759e4694f85.png)

Perhaps we can have a unique background color for slots with equipped items inside the offset window like this:

![image](https://user-images.githubusercontent.com/468153/182994045-947b3c4f-1dfd-4ef3-a5f4-5d117a579e44.png)

Or maybe there's a better way to indicate slots within the offset window that doesn't use background color, like an icon in the top right corner for example. (I'm not sure how well the red works for colorblind users anyway.)

**Comment by iTNTPiston** [comment]
We already display `(Count=X)` to indicate how many offset slots (i.e. broken slots) there are. There could be something better but this is a minor issue

**Comment by jordanbtucker** [comment]
I respect that you feel like this is a minor issue. I may put a bit more weight on user experience than you do. You say there could be something better, and that's what I'm proposing. It would be one small change to the CSS. Can you elaborate on why you don't like this solution?

As far a the severity of this issue, it is possible to figure out whether an equipped item is included in the offset window by counting from either the front or end of the inventory, but it becomes increasingly more error prone as the inventory size grows.

Since the red background is the most common way users determine whether an item is within the offset window, it becomes easy to mistake whether equipped items are included, leading to errors, potentially causing users to lose time in both failed execution in game due to incorrect steps and in troubleshooting where the error occurred. Making a small, easy change like this can help avoid those situations, resulting in a better user experience.

Thank you for your consideration.

**Comment by iTNTPiston** [comment]
I agree that it's a bit inconvenient that the equipped color overrides the offset indicator. However, IMO adding a third color would just confuses the user. It's not intuitive to connect purple = blue + red = equipped + offset.

It's probably better to use another indicator than the red background so it doesn't conflict with the equipped indicator. However, we also plan to add modifier support in the future, which means we need to display modifier icon, modifier value, potion duration, etc. We don't want the slot to become too cluttered with all those info displayed.

**Comment by iTNTPiston** [comment]
Maybe expand the red background to cover the margin between the slots so it's visible behind the equipped indicator

**Comment by OnlineCop** [comment]
One possible CSS effect for when a span contains both `.ItemSlotBroken` and `.ItemSlotEquipped` classes could be: `background:linear-gradient(-45deg, rgb(102,0,0)50%, rgb(0, 136, 255)50%)`.

That would look something like this:
![image](https://user-images.githubusercontent.com/1168697/200433560-4b91e800-f924-421b-bce5-332572393b38.png)

**Comment by iTNTPiston** [comment]
I am migrating the project to iTNTPiston/botw-ist and upgrading everything including UI and simulation core. Issues/bugs can still be discussed here but I will archive this repo once the transition finishes

I am going with this in the new experience
![image](https://user-images.githubusercontent.com/44533763/200442928-4fc74f76-ee53-468d-b0ce-7a26e767fea8.png)
